## Cálculo de $V_0$ y $V_{LS}$ para la energía de los niveles inferior y superior de Fermi para distintos isótopos.

NOTA: Cambiar la variable camino / file_path / os.chdir según el fichero en el que estemos trabajando

Primero vamos a crear una pequeña base de datos con la energía de los distintos núcleos y sus paridades, a partir de la tabla que aparece en las prácticas

In [24]:
## Librerías que vamos a utilizar

import numpy as np
import pandas as pd

In [25]:
# Crear los datos
data = {
    'Núcleo': [
        '5Li', '5He', '3He', '3H', '4He',
        '13N', '13C', '11C', '11B', '12C',
        '17F', '17O', '15O', '15N', '16O',
        '41Sc', '41Ca', '39Ca', '39K', '40Ca',
        '49Sc', '49Ca', '47Ca', '47K', '48Ca',
        '91Nb', '91Zr', '89Zr', '89Y', '90Zr',
        '149Tb', '147Gd', '145Gd', '145Eu', '146Gd',
        '209Bi', '209Pb', '207Pb', '207Tl', '208Pb'
    ],
    'Δ (MeV)': [
        11.685, 11.390, 14.930, 14.950, 2.420,
        5.436, 3.125, 10.650, 8.668, 0.000,
        1.952, -0.810, 2.855, 0.102, -4.737,
        -28.644, -35.139, -27.282, -33.806, -34.847,
        -46.555, -41.286, -42.343, -35.698, -44.216,
        -86.637, -87.893, -84.860, -87.695, -89.765,
        -70.510, -75.207, -72.940, -77.936, -75.361,
        -18.268, -17.624, -22.463, -21.041, -21.759
    ],
    'Jπ': [
        '3/2−', '3/2−', '1/2+', '1/2+', '0+',
        '1/2−', '1/2−', '3/2−', '3/2−', '0+',
        '5/2+', '5/2+', '1/2−', '1/2−', '0+',
        '7/2−', '7/2−', '3/2+', '3/2+', '0+',
        '7/2−', '3/2−', '7/2−', '1/2+', '0+',
        '9/2+', '5/2+', '9/2+', '1/2−', '0+',
        '11/2−', '7/2−', '1/2+', '5/2+', '0+',
        '9/2−', '9/2+', '1/2−', '1/2+', '0+'
    ],

## Metemos Z y A pa poder mejorar el código -> A partir de El núcleo, se meten A y Z y se suman y restan para las energías.

    'Z': [
        3, 2, 2, 1, 2,
        7, 6, 6, 5, 6,
        9, 8, 8, 7, 8,
        21, 20, 20, 19, 20,
        21, 20, 20, 19, 20,
        41, 40, 40, 39, 40,
        65, 64, 64, 63, 64,
        83, 82, 82, 81, 82
    ],
    'A': [
        5, 5, 3, 3, 4,
        13, 13, 11, 11, 12,
        17, 17, 15, 15, 16,
        41, 41, 39, 39, 40,
        49, 49, 47, 47, 48,
        91, 91, 89, 89, 90,
        149, 147, 145, 145, 146,
        209, 209, 207, 207, 208
    ]
}

# Crear el DataFrame
df = pd.DataFrame(data)

df['N'] = df['A'] - df['Z']

df['R'] = round(1.2 * df['A']**(1/3),2)

# Mostrar el DataFrame
df

Núcleo  Δ (MeV)     Jπ   Z    A    N     R
0     5Li   11.685   3/2−   3    5    2  2.05
1     5He   11.390   3/2−   2    5    3  2.05
2     3He   14.930   1/2+   2    3    1  1.73
3      3H   14.950   1/2+   1    3    2  1.73
4     4He    2.420     0+   2    4    2  1.90
5     13N    5.436   1/2−   7   13    6  2.82
6     13C    3.125   1/2−   6   13    7  2.82
7     11C   10.650   3/2−   6   11    5  2.67
8     11B    8.668   3/2−   5   11    6  2.67
9     12C    0.000     0+   6   12    6  2.75
10    17F    1.952   5/2+   9   17    8  3.09
11    17O   -0.810   5/2+   8   17    9  3.09
12    15O    2.855   1/2−   8   15    7  2.96
13    15N    0.102   1/2−   7   15    8  2.96
14    16O   -4.737     0+   8   16    8  3.02
15   41Sc  -28.644   7/2−  21   41   20  4.14
16   41Ca  -35.139   7/2−  20   41   21  4.14
17   39Ca  -27.282   3/2+  20   39   19  4.07
18    39K  -33.806   3/2+  19   39   20  4.07
19   40Ca  -34.847     0+  20   40   20  4.10
20   49Sc  -46.555   7/2−  21   49   28  4.39
21   49Ca  -41.286   3/2−  20   49   29  4.39
22   47Ca  -42.343   7/2−  20   47   27  4.33
23    47K  -35.698   1/2+  19   47   28  4.33
24   48Ca  -44.216     0+  20   48   28  4.36
25   91Nb  -86.637   9/2+  41   91   50  5.40
26   91Zr  -87.893   5/2+  40   91   51  5.40
27   89Zr  -84.860   9/2+  40   89   49  5.36
28    89Y  -87.695   1/2−  39   89   50  5.36
29   90Zr  -89.765     0+  40   90   50  5.38
30  149Tb  -70.510  11/2−  65  149   84  6.36
31  147Gd  -75.207   7/2−  64  147   83  6.33
32  145Gd  -72.940   1/2+  64  145   81  6.30
33  145Eu  -77.936   5/2+  63  145   82  6.30
34  146Gd  -75.361     0+  64  146   82  6.32
35  209Bi  -18.268   9/2−  83  209  126  7.12
36  209Pb  -17.624   9/2+  82  209  127  7.12
37  207Pb  -22.463   1/2−  82  207  125  7.10
38  207Tl  -21.041   1/2+  81  207  126  7.10
39  208Pb  -21.759     0+  82  208  126  7.11

Una vez creada la base de datos, podemos crear la función energía_nivel(Nucleos) que nos devolverá una tabla con todos los datos que queremos (Energías superior e inferior de fermi para protones y neutrones de cada isótopo)

In [26]:
############## DEFINITIVO ###################

def energia_nivel(Nucleos, Deltaneutron=8.071, Deltaproton=7.288):
    
    data = {
        'E_F superior (neutron)': [],
        'E_F inferior (neutron)': [],
        'E_F superior (proton)': [],
        'E_F inferior (proton)': []
    }

    for nucleo in Nucleos:

        # Obtener N y Z del núcleo actual
        N = df.loc[df['Núcleo'] == nucleo, 'N'].values[0]
        Z = df.loc[df['Núcleo'] == nucleo, 'Z'].values[0]

        # Energía del nivel actual
        e_nivel = df.loc[df['Núcleo'] == nucleo, 'Δ (MeV)'].values[0]

        # Niveles de neutrones
        try:
            neutron_posterior = df.loc[(df['N'] == N+1) & (df['Z'] == Z), 'Núcleo'].values[0]
            e_posterior_neutron = df.loc[df['Núcleo'] == neutron_posterior, 'Δ (MeV)'].values[0]
            energia_superior_neutron = e_posterior_neutron - e_nivel - Deltaneutron
        except IndexError:
            energia_superior_neutron = None  # Si no hay datos

        try:
            neutron_anterior = df.loc[(df['N'] == N-1) & (df['Z'] == Z), 'Núcleo'].values[0]
            e_anterior_neutron = df.loc[df['Núcleo'] == neutron_anterior, 'Δ (MeV)'].values[0]
            energia_inferior_neutron = e_nivel - e_anterior_neutron - Deltaneutron
        except IndexError:
            energia_inferior_neutron = None

        # Niveles de protones
        try:
            proton_posterior = df.loc[(df['Z'] == Z+1) & (df['N'] == N), 'Núcleo'].values[0]
            e_posterior_proton = df.loc[df['Núcleo'] == proton_posterior, 'Δ (MeV)'].values[0]
            energia_superior_proton = e_posterior_proton - e_nivel - Deltaproton
        except IndexError:
            energia_superior_proton = None

        try:
            proton_anterior = df.loc[(df['Z'] == Z-1) & (df['N'] == N), 'Núcleo'].values[0]
            e_anterior_proton = df.loc[df['Núcleo'] == proton_anterior, 'Δ (MeV)'].values[0]
            energia_inferior_proton = e_nivel - e_anterior_proton - Deltaproton
        except IndexError:
            energia_inferior_proton = None

        # Almacenar los resultados en listas correspondientes
        data['E_F superior (neutron)'].append(energia_superior_neutron)
        data['E_F inferior (neutron)'].append(energia_inferior_neutron)
        data['E_F superior (proton)'].append(energia_superior_proton)
        data['E_F inferior (proton)'].append(energia_inferior_proton)

    # Convertir el diccionario en DataFrame y establecer Nucleos como columnas
    tabla = pd.DataFrame(data, index=Nucleos).T  # Usar .T para transponer y hacer de Nucleos las columnas

    return tabla


Para los núcleos que nos ocupan:

In [27]:
magicos = ['12C', '16O', '40Ca', '48Ca']

Niveles_nucleos = energia_nivel(Nucleos=magicos)

Vamos a añadirle a cada isótopo sus estados:

In [28]:
# Valores para los nuevos orbitales
orbital_sup_prot = {
    '12C': [1, 1, 1, 1, 1],
    '16O': [1, 1, 1, 2, 3],
    '40Ca': [1, 1, 1, 3, 4],
    '48Ca': [1, 1, 1, 3, 4]
}

orbital_inf_prot = {
    '12C': [0, 1, 1, 1, 2],
    '16O': [0, 1, 1, 1, 2],
    '40Ca': [0, 1, 1, 2, 2],
    '48Ca': [0, 1, 1, 2, 2]
}

orbital_sup_neut = {
    '12C': [1, 0, 1, 1, 1],
    '16O': [1, 0, 1, 2, 3],
    '40Ca': [1, 0, 1, 3, 4],
    '48Ca': [0, 0, 1, 3, 4]
}

orbital_inf_neut = {
    '12C': [0, 0, 1, 1, 2],
    '16O': [0, 0, 1, 1, 2],
    '40Ca': [0, 0, 1, 2, 2],
    '48Ca': [1, 1, 2, 1, 2]
}

# Añadir nuevas columnas al DataFrame
Niveles_nucleos.loc['orbital_sup_prot'] = [orbital_sup_prot['12C'], orbital_sup_prot['16O'], orbital_sup_prot['40Ca'], orbital_sup_prot['48Ca']]
Niveles_nucleos.loc['orbital_inf_prot'] = [orbital_inf_prot['12C'], orbital_inf_prot['16O'], orbital_inf_prot['40Ca'], orbital_inf_prot['48Ca']]
Niveles_nucleos.loc['orbital_sup_neut'] = [orbital_sup_neut['12C'], orbital_sup_neut['16O'], orbital_sup_neut['40Ca'], orbital_sup_neut['48Ca']]
Niveles_nucleos.loc['orbital_inf_neut'] = [orbital_inf_neut['12C'], orbital_inf_neut['16O'], orbital_inf_neut['40Ca'], orbital_inf_neut['48Ca']]

# Mostrar el DataFrame actualizado
Niveles_nucleos.head(8)

12C              16O             40Ca  \
E_F superior (neutron)           -4.946           -4.144           -8.363   
E_F inferior (neutron)          -18.721          -15.663          -15.636   
E_F superior (proton)            -1.852           -0.599           -1.085   
E_F inferior (proton)           -15.956          -12.127           -8.329   
orbital_sup_prot        [1, 1, 1, 1, 1]  [1, 1, 1, 2, 3]  [1, 1, 1, 3, 4]   
orbital_inf_prot        [0, 1, 1, 1, 2]  [0, 1, 1, 1, 2]  [0, 1, 1, 2, 2]   
orbital_sup_neut        [1, 0, 1, 1, 1]  [1, 0, 1, 2, 3]  [1, 0, 1, 3, 4]   
orbital_inf_neut        [0, 0, 1, 1, 2]  [0, 0, 1, 1, 2]  [0, 0, 1, 2, 2]   

                                   48Ca  
E_F superior (neutron)           -5.141  
E_F inferior (neutron)           -9.944  
E_F superior (proton)            -9.627  
E_F inferior (proton)           -15.806  
orbital_sup_prot        [1, 1, 1, 3, 4]  
orbital_inf_prot        [0, 1, 1, 2, 2]  
orbital_sup_neut        [0, 0, 1, 3, 4]  
orbital_inf_neut        [1, 1, 2, 1, 2]

Vamos a crear una serie de funciones para automatizar la minimización de valores de $V_0$ y $V_{LS}$ para cada núcleo

In [29]:
import subprocess
import os
import re

Lo primero es introducir el path en el que estamos trabajando (la carpeta en la que tengamos el wsmod_W.exe).

In [30]:
os.chdir('C:\\Users\\migue\\Desktop\\WS\\WS_modificado')

In [31]:
Ca40 = '40Ca'
C12 = '12C'
O16 = '16O'
Ca48 = '48Ca'

In [32]:
# Llamamos "comando" al comando que usaríamos en terminal para crear los
# ficheros que hemos definido en la celda anterior. 

def comando(nucleo):
    comando = "wsmod_W.exe < wsnum.inp >" + ' ' + nucleo + '.txt'
    return comando

filas = 4   ## El número de filas a partir del cuál empiezan los valores de
            ## Energía n'el fichero

## Corremos el proceso que queremos en terminal.

def proceso(nucleo):
    proceso = subprocess.run(comando(nucleo), shell=True, capture_output=True, text=True)
    data_P = pd.read_csv(nucleo + '.txt', header = filas)                                   ##header viendo donde empezamos a contar
    return data_P

Por poner un ejemplo para ver cómo se vería el Calcio:

In [33]:
print(proceso(Ca40))

   NR. PROTON STATES=  7  NR. NEUTRON STATES= 10
0                          0  1  1  0  1 -33.700
1                          0  1  1  1  2 -23.946
2                          0  1  1  1  1 -21.701
3                          0  1  1  2  3 -13.169
4                          0  1  2  0  1  -8.552
5                          0  1  1  2  2  -8.397
6                          1  1  1  3  4  -1.819
7                          0  0  1  0  1 -47.238
8                          0  0  1  1  1 -36.706
9                          0  0  1  1  2 -35.459
10                         0  0  1  2  2 -24.620
11                         0  0  1  2  3 -21.917
12                         0  0  2  0  1 -20.144
13                         1  0  1  3  3 -11.707
14                         1  0  2  1  1  -7.635
15                         1  0  1  3  4  -7.349
16                         1  0  2  1  2  -6.291


Ahora, creamos la función sacar energía, que nos devuelva las energías superior e inferior del fichero.

In [34]:
def sacar_energia(nucleo, pn): ## PN es 0 para neutrones 1 para protones.

    data = proceso(nucleo)

    ## Cogemos los valores correspondientes.

    if pn == 0:
        estado_inferior_inp = Niveles_nucleos[nucleo]['orbital_inf_neut']
        estado_superior_inp = Niveles_nucleos[nucleo]['orbital_sup_neut']

    else:
        estado_inferior_inp = Niveles_nucleos[nucleo]['orbital_inf_prot']
        estado_superior_inp = Niveles_nucleos[nucleo]['orbital_sup_prot']

    ## Transformamos los datos a listas de enteros.

    ## inicializamos el array

    datos_transf = np.zeros((len(data),6))

    ## Transformamos los datos

    for i in range(len(data)):

        ## Los convertimos fila a fila en una lista de enteros
        datos_transf[i] = [float(num) for num in data.values[i][0].split()]

        ## Consideramos para evaluar el estado hueco/part , proton/neutron , n , l , j+12
        estado_i = datos_transf[i][:5]

        if np.all(estado_i == estado_inferior_inp):
            energia_inferior = datos_transf[i,-1]

        if np.all(estado_i == estado_superior_inp):
            energia_superior = datos_transf[i,-1]    


    return np.array([energia_inferior,energia_superior])


Ahora creamos una función que nos permita modificar el fichero.

In [35]:

## CAMBIAR EL PATH SEGÚN DÓNDE LO TENGAS ##
camino = 'C:\\Users\\migue\\Desktop\\WS\\WS_modificado\\wsnum.inp'


def modificar_isotopo(file_path,nucleo,tipo):

    # Leer el contenido del archivo
    with open(file_path, 'r') as file:
        lineas = file.readlines()

    # Separar elementos
    elementos_separados = []
    for linea in lineas:
        elementos = linea.strip().split()
        elementos_separados.extend(elementos)

    ## Modificar A,Z
        ## A

    A = df.loc[df['Núcleo'] == nucleo, 'A'].values[0]
    elementos_separados[3] = str(A)

        ## Z

    Z = df.loc[df['Núcleo'] == nucleo, 'Z'].values[0]
    elementos_separados[4] = str(Z)

    ## Modificar Radio

    if tipo == 1:
        elementos_separados[14] = str(df.loc[df['Núcleo'] == nucleo, 'R'].values[0])
        elementos_separados[17] = str(df.loc[df['Núcleo'] == nucleo, 'R'].values[0])
        elementos_separados[19] = str(df.loc[df['Núcleo'] == nucleo, 'R'].values[0])

    else:
        elementos_separados[21] = str(df.loc[df['Núcleo'] == nucleo, 'R'].values[0])
        elementos_separados[24] = str(df.loc[df['Núcleo'] == nucleo, 'R'].values[0])
        elementos_separados[26] = str(0)
    
    # Volver a escribir el archivo manteniendo el formato original
    with open(file_path, 'w') as file:
        # Inicializar un índice para ir agregando los elementos a las líneas
        indice = 0

        for linea in lineas:
            # Limpiar la línea y obtener la cantidad de elementos en la línea original
            elementos_linea = linea.strip().split()

            # Crear una nueva línea con los elementos modificados
            nueva_linea = []
            for _ in elementos_linea:
                if indice < len(elementos_separados):
                    nueva_linea.append(elementos_separados[indice])
                    indice += 1

            # Unir los elementos de la nueva línea y escribir
            file.write('   '.join(nueva_linea) + '\n')


def modificar_v(file_path, tipo, nuevo_v0, nuevo_vls):
    # Leer el contenido del archivo
    with open(file_path, 'r') as file:
        lineas = file.readlines()

    # Separar elementos
    elementos_separados = []
    for linea in lineas:
        elementos = linea.strip().split()
        elementos_separados.extend(elementos)
    
    if tipo==1:

        # Modificar V0 y VLS
        elementos_separados[13] = str(nuevo_v0)  # Cambiar V0 (elemento 13)
        elementos_separados[16] = str(nuevo_vls)  # Cambiar VLS (elemento 16)

    else: 
        
        # Modificar V0 y VLS
        elementos_separados[20] = str(nuevo_v0) 
        elementos_separados[23] = str(nuevo_vls) 
        

    # Volver a escribir el archivo manteniendo el formato original
    with open(file_path, 'w') as file:
        # Inicializar un índice para ir agregando los elementos a las líneas
        indice = 0

        for linea in lineas:
            # Limpiar la línea y obtener la cantidad de elementos en la línea original
            elementos_linea = linea.strip().split()

            # Crear una nueva línea con los elementos modificados
            nueva_linea = []
            for _ in elementos_linea:
                if indice < len(elementos_separados):
                    nueva_linea.append(elementos_separados[indice])
                    indice += 1

            # Unir los elementos de la nueva línea y escribir
            file.write('   '.join(nueva_linea) + '\n')


In [36]:
## Función para automatizar el cambio en los valores de V0, VLS y sacar energía:

def ENERGIA(nucleo,pn,V0,VLS,camino = 'C:\\Users\\migue\\Desktop\\WS\\WS_modificado\\wsnum.inp'):
    modificar_v(file_path=camino, tipo=pn, nuevo_v0=V0, nuevo_vls=VLS)
    output = sacar_energia(nucleo = nucleo, pn=pn)
    return output

Creamos una función para minimizar los parámetros v0 y vls

In [37]:
def f_min(nucleo,tipo, V0, VLS, f=ENERGIA):

    if tipo == 0:
        valores_teo = [Niveles_nucleos[nucleo]['E_F inferior (neutron)'] , Niveles_nucleos[nucleo]['E_F superior (neutron)']]
    else:
        valores_teo = [Niveles_nucleos[nucleo]['E_F inferior (proton)'] , Niveles_nucleos[nucleo]['E_F superior (proton)']]
    return np.array([abs(valores_teo[0] - f(nucleo, tipo, V0, VLS)[0]), 
                     abs(valores_teo[1] - f(nucleo, tipo ,V0, VLS)[1])])

Y ahora lo importante: Creamos una función que nos permita minimizar la función anterior, de forma que, iterativamente, calcule el valor óptimo de V0 y VLS

In [38]:
## Jacobian calculation for a vector-valued function
def jacobian(nucleo,tipo,V0, VLS, h=1e-2, f=f_min):
    J = np.zeros((2, 2))  # Jacobian matrix (2x2)
    
    # Partial derivatives for f1 (component 1 of f)
    J[0, 0] = (f(nucleo,tipo,V0+h, VLS)[0] - f(nucleo,tipo,V0, VLS)[0]) / h  # df1/dV0
    J[0, 1] = (f(nucleo,tipo,V0, VLS+h)[0] - f(nucleo,tipo,V0, VLS)[0]) / h  # df1/dVLS
    
    # Partial derivatives for f2 (component 2 of f)
    J[1, 0] = (f(nucleo,tipo,V0+h, VLS)[1] - f(nucleo,tipo,V0, VLS)[1]) / h  # df2/dV0
    J[1, 1] = (f(nucleo,tipo,V0, VLS+h)[1] - f(nucleo,tipo,V0, VLS)[1]) / h  # df2/dVLS

    return J

def jacobian_gradient_descent(nucleo,tipo,eta1,eta2,tolerancia,max_iter,v0,vls): ## V0, VLS Son los valores iniciales con los que empezamos a iterar.

    ## Bucle de Gradient Descent:
    for i in range(max_iter):
    ## Jacobiano en la posición actual
        J = jacobian(nucleo,tipo,v0, vls)

    ## Valor de la función f en la posición actual
        f_val = f_min(nucleo,tipo,v0, vls)

    ## Imprime los valores de f_min y el Jacobiano para debug
        print(f"Iteración {i}: f_min = {f_val}, Jacobiano = \n{J}")

    ## Calcular el gradiente (dirección negativa de los valores de la función)
        gradient = -J.T @ f_val  # Producto del Jacobiano transpuesto por el valor de f_min

    ## Imprimir el gradiente para ver si es muy grande
        print(f"Gradiente = {gradient}")
        print(f'Energías: inferior = {round(f_val[0],3)}, superior = {round(f_val[1],3)}')
    

    ## Actualización de las variables
        v0_new = v0 + eta1 * gradient[0]
        vls_new = vls + eta2 * gradient[1]

        if round(f_min(nucleo,tipo,v0_new,vls_new)[0],3) <= tolerancia and round(f_min(nucleo,tipo,v0_new,vls_new)[1],3) <= tolerancia:
            print(f"Converged after {i} iterations.")
            break

    ## Actualizar variables para la siguiente iteración
        v0, vls = v0_new, vls_new

        print(f"v0 = {v0}, vls = {vls}, Iteración = {i}")


    v0, vls = v0_new, vls_new

    print(f'Minimum found at:\n V_0 = {v0}, V_LS = {vls}')

# $^{40}Ca$ 

## Protones

In [16]:
modificar_isotopo(camino,Ca40,tipo=1)

jacobian_gradient_descent(nucleo=Ca40,tipo=1,eta1=5e-2,eta2=5e-2,tolerancia=3e-3,max_iter=10000,v0=-55.0,vls=-7.0)

Iteración 0: f_min = [0.068 0.734], Jacobiano = 
[[-0.7  0.4]
 [-0.6 -0.4]]
Gradiente = [0.488  0.2664]
Energías: inferior = 0.068, superior = 0.734
v0 = -54.9756, vls = -6.98668, Iteración = 0
Iteración 1: f_min = [0.055 0.713], Jacobiano = 
[[-0.8  0.4]
 [-0.6 -0.4]]
Gradiente = [0.4718 0.2632]
Energías: inferior = 0.055, superior = 0.713
v0 = -54.95201, vls = -6.97352, Iteración = 1
Iteración 2: f_min = [0.042 0.692], Jacobiano = 
[[-0.7  0.4]
 [-0.6 -0.4]]
Gradiente = [0.4446 0.26  ]
Energías: inferior = 0.042, superior = 0.692
v0 = -54.92978, vls = -6.96052, Iteración = 2
Iteración 3: f_min = [0.031 0.673], Jacobiano = 
[[-0.8  0.4]
 [-0.7 -0.5]]
Gradiente = [0.4959 0.3241]
Energías: inferior = 0.031, superior = 0.673
v0 = -54.904985, vls = -6.944315, Iteración = 3
Iteración 4: f_min = [0.018 0.65 ], Jacobiano = 
[[-0.7  0.4]
 [-0.6 -0.5]]
Gradiente = [0.4026 0.3178]
Energías: inferior = 0.018, superior = 0.65
v0 = -54.884855, vls = -6.928424999999999, Iteración = 4
Iteración 5: f

## Neutrones

In [39]:
modificar_isotopo(camino,Ca40,tipo=0)

jacobian_gradient_descent(nucleo=Ca40,tipo=0,eta1=5e-2,eta2=5e-2,tolerancia=3e-3,max_iter=10000,v0=-55.0,vls=-7.0)



Iteración 0: f_min = [0.683 0.74 ], Jacobiano = 
[[-0.8  0.3]
 [-0.6 -0.4]]
Gradiente = [0.9904 0.0911]
Energías: inferior = 0.683, superior = 0.74
v0 = -54.95048, vls = -6.995445000000002, Iteración = 0
Iteración 1: f_min = [0.646 0.706], Jacobiano = 
[[-0.8  0.3]
 [-0.6 -0.5]]
Gradiente = [0.9404 0.1592]
Energías: inferior = 0.646, superior = 0.706
v0 = -54.90346, vls = -6.9874849999999995, Iteración = 1
Iteración 2: f_min = [0.612 0.672], Jacobiano = 
[[-0.8  0.4]
 [-0.7 -0.5]]
Gradiente = [0.96   0.0912]
Energías: inferior = 0.612, superior = 0.672
v0 = -54.855459999999994, vls = -6.98292499999999, Iteración = 2
Iteración 3: f_min = [0.576 0.639], Jacobiano = 
[[-0.8  0.4]
 [-0.7 -0.5]]
Gradiente = [0.9081 0.0891]
Energías: inferior = 0.576, superior = 0.639
v0 = -54.81005499999999, vls = -6.978469999999992, Iteración = 3
Iteración 4: f_min = [0.542 0.607], Jacobiano = 
[[-0.7  0.4]
 [-0.6 -0.4]]
Gradiente = [0.7436 0.026 ]
Energías: inferior = 0.542, superior = 0.607
v0 = -54.7728